project:
  type: website
  output-dir: docs
  resources:
    - _headers

website:
  title: Portfolio
  repo-url: https://github.com/NishantBharali/Blog
  repo-actions: [source]
  site-url: https://www.nishantkb.info/
  favicon: images/NB_logo.webp
  search: 
    location: navbar
    type: overlay
    limit: 10
    copy-button: true
  back-to-top-navigation: true
  page-footer:
    border: true
    left: |
      Powered by [Quarto](https://quarto.org)
    center: |
      &copy; 2024, Nishant Bharali
    right: |
      License: [CC BY NC SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0).
      
    #   - icon: linkedin
    #     href: https://www.linkedin.com/in/nishant-kumar-bharali/
    #     text: LinkedIn
    #   - icon: github
    #     href: https://github.com/NishantBharali
    #     text: GitHub
    #   - icon: stack-overflow
    #     href: https://stackoverflow.com/users/18371927/nishant
    #     text: Stack Overflow
    #   - icon: envelope
    #     href: mailto:nishantkb@vt.edu
    #     text: Mail
  open-graph:
    site-name: Nishant Bharali's Portfolio
  cookie-consent: true
  twitter-card: 
    image: images/Nishant.jpg
    card-style: summary_large_image
    creator: "@NishantBharali"
  navbar:
    right:
      - text: Projects
        menu:
          - text: "Machine Learning"
            href: blog.qmd
          - text: "Control Systems"
            href: control_systems.qmd
          - text: "Robotics"
            href: robotics.qmd
          - text: "Machine Vision"
            href: Vision.qmd
      - text: About
        href: about.qmd
      - text: Tools
        href: tool.qmd
      - text: Resources
        menu:
          - text: "Nishant's Resources"
            href: resources.qmd
          - text: Modern Robotics
            href: https://drive.google.com/file/d/1TjYOeJ2PO4z16hSjQkF8PNFojcGU9IYz/view
            target: _blank
          - text: Robot Modelling and Control
            href: https://drive.google.com/file/d/1lkGRqrfiMyiOY6Ct4ihws7DEymHVjtjC/view
            target: _blank
          - text: Python for Data Science
            href: https://r4ds.hadley.nz/
            target: _blank
      - text: Contact
        menu:
          - icon: linkedin
            href: https://www.linkedin.com/in/nishant-kumar-bharali/
            target: _blank
            text: LinkedIn
          - icon: github
            href: https://github.com/NishantBharali
            target: _blank
            text: GitHub
          - icon: stack-overflow
            href: https://stackoverflow.com/users/18371927/nishant
            target: _blank
            text: Stack Overflow
          - icon: envelope
            href: mailto:nishantkb@vt.edu
            text: Gmail
          - href: cv/cv.html
            icon: file-earmark-person-fill
            text: Curriculum Vitae
  
  sidebar:
    style: "docked"
    search: false
    sort: order
    collapse-level: 1
    overflow-y: auto
    contents:
      - text: "Home"
        file: index.qmd
      - section: Projects
        file: Projects.qmd
        contents:
          - section: Robotics
            href: robotics.html#category=Robotics
            contents:
              - href: Robotics/Inverse_kinematics.qmd
                text: "Inverse Kinematics"
              - href: Robotics/Potential_trajectory.qmd
                text: "Trajectory Optimization"
              - href: Robotics/Dynamics.qmd
                text: "Dynamics"
              - href: Robotics/Control.qmd
                text: "Control"
              - href: Robotics/RRT.qmd
                text: "RRT"
          - section: Control System
            href: control_systems.html#category=Control
            contents:
              - href: Control Systems/Full_State_Feedback_Control_Design.qmd
                text: "Control Design II"
              - href: Control Systems/Linearized_LTI_Modeling_Feedback_Control.qmd
                text: "LTI Modeling"
              - href: Control Systems/Bode_freqresp.qmd
                text: "Bode Estimation"
          - section: Machine Learning
            href: blog.html#category=Machine Learning
            contents:
              - href: posts/Random Processes/index.qmd
                text: "Probability"
              - href: posts/Linear and Non Linear Regression/index.qmd
                text: "Regression"
              - href: posts/Clustering/index.qmd
                text: "Clustering"
              - href: posts/Classification/index.qmd
                text: "Classification"
              - href: posts/Anomaly-Outlier Detection/index.qmd
                text: "Anamoly"
          - section: Machine Vision
            href: Vision.html#category=Vision
            contents:
              - href: CV_Project/CV_project.qmd
                text: "Fire Detection"
      - text: "About Me"
        file: about.qmd
      - section: Tools
        file: tool.qmd
        contents:
          - href: Tools/git/git.qmd
            text: "Git"
          - href: Tools/quarto/quarto.qmd
            text: "Quarto"
      - section: "Resources"
        contents:
          - text: "My Resources"
            href: resources.qmd
          - text: Modern Robotics
            href: https://drive.google.com/file/d/1TjYOeJ2PO4z16hSjQkF8PNFojcGU9IYz/view
            target: _blank
          - text: Robot Modelling and Control
            href: https://drive.google.com/file/d/1lkGRqrfiMyiOY6Ct4ihws7DEymHVjtjC/view
            target: _blank
          - text: Python for Data Science
            href: https://r4ds.hadley.nz/
            target: _blank

format:
  html:
    page-layout: full
    theme:
      light: [flatly, theme-light.scss]
      dark: [darkly, theme-dark.scss]
    css: styles.css
    lang: en
    grid:
      sidebar-width: 150px
      body-width: 1800px
      margin-width: 250px
    fontsize: 1.0em
    code-copy: true
    code-overflow: wrap
    include-after-body:
      - text: |
          <script type="text/javascript">
          const dateElements = document.querySelectorAll("p.date, div.listing-date");
          dateElements.forEach((el) => {
            el.innerHTML = el.innerHTML.replace(
              /(\d+)(rd|st|th)/g,
              "$1<sup style='font-size:0.5em;font-style:italic;'>$2</sup>"
            );
          });
          </script>

webr: 
  show-startup-message: false
  show-header-message: false
  channel-type: 'post-message'

execute:
  freeze: true
  cache: true